Added belgium support to Checkout
myparcelnl/checkout pull request #21
Opened 2017-08-04 12:21 UTC by walteradrichem

2017-08-04 12:36 UTC, reindert-vetter requested changes
I will make an example for BE

2017-08-04 13:45 UTC, funonly commented on js/myparcel.coffee
> +    window.mypa.isNational = window.mypa.settings.cc is NATIONAL
Rather not place needlessly boolean checks in the window object

2017-08-04 13:53 UTC, SimonCsoma requested changes
you have to show the price at BE shipments

2017-08-07 14:46 UTC, reindert-vetter approved these changes

2017-10-24 13:45 UTC, merged